### ISSUE TITLE
Software的IBL有问题，opengl和vulkan的没问题

### ISSUE THREAD

**Issue by GraphicsEnthusiast** [keith2018/SoftGLRender#46]
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/24b9a8d3-180a-4dab-b473-b9e829fca3b7)
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/a60a93a6-4ad1-4ec1-85d0-a4394e7c2e97)
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/1c67f636-2032-4c09-bbcd-9ef1d75b9e13)
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/aa8bd4aa-2131-4b3b-ab0e-c96b0ec1cd7c)
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/b6a4e59b-770a-468f-9f49-2bad0b283d40)
![image](https://github.com/keith2018/SoftGLRender/assets/75780167/bf5cc0d6-2404-4a55-95da-5423cf962625)

**Comment by keith2018** [comment]
把 cache 目录删了后是正常的吗？

**Comment by GraphicsEnthusiast** [comment]
> 把 cache 目录删了后是正常的吗？

删除后正常了，谢谢

**Comment by keith2018** [comment]
> > 把 cache 目录删了后是正常的吗？
> 
> 删除后正常了，谢谢

你电脑上生成的 IBL 的 cache 和仓库自带的不一样吗？这里 cache 逻辑实现比较简单，可能存在兼容性问题，有兴趣的话帮忙定位下，感谢~

**Comment by GraphicsEnthusiast** [comment]
> > > 把 cache 目录删了后是正常的吗？
> > 
> > 
> > 删除后正常了，谢谢
> 
> 你电脑上生成的 IBL 的 cache 和仓库自带的不一样吗？这里 cache 逻辑实现比较简单，可能存在兼容性问题，有兴趣的话帮忙定位下，感谢~

我目前是初学者，要定位估计我的能力不允许😭我自己写了一个离线的软光追渲染器：https://github.com/GraphicsEnthusiast/DreamRender/tree/stage-1
想再写个软光栅，在知乎上看到您的那个回答，我很喜欢这个项目，想模仿这个写😂

**Comment by keith2018** [comment]
> 

哈哈没事，可能是文件 IO 问题导致 cache 读错了，后面我再找找其他设备查下；
你的项目很赞！有关软光栅的问题，可以随时开 issue 一起探讨~

**Comment by keith2018** [comment]
> > > > 把 cache 目录删了后是正常的吗？
> > > 
> > > 
> > > 删除后正常了，谢谢
> > 
> > 
> > 你电脑上生成的 IBL 的 cache 和仓库自带的不一样吗？这里 cache 逻辑实现比较简单，可能存在兼容性问题，有兴趣的话帮忙定位下，感谢~
> 
> 我目前是初学者，要定位估计我的能力不允许😭我自己写了一个离线的软光追渲染器：https://github.com/GraphicsEnthusiast/DreamRender/tree/stage-1 想再写个软光栅，在知乎上看到您的那个回答，我很喜欢这个项目，想模仿这个写😂

哈哈没事，可能是文件 IO 问题导致 cache 读错了，后面我再找找其他设备查下；
你的项目很赞！有关软光栅的问题，可以随时开 issue 一起探讨~

**Comment by GraphicsEnthusiast** [comment]
> > > > > 把 cache 目录删了后是正常的吗？
> > > > 
> > > > 
> > > > 删除后正常了，谢谢
> > > 
> > > 
> > > 你电脑上生成的 IBL 的 cache 和仓库自带的不一样吗？这里 cache 逻辑实现比较简单，可能存在兼容性问题，有兴趣的话帮忙定位下，感谢~
> > 
> > 
> > 我目前是初学者，要定位估计我的能力不允许😭我自己写了一个离线的软光追渲染器：https://github.com/GraphicsEnthusiast/DreamRender/tree/stage-1 想再写个软光栅，在知乎上看到您的那个回答，我很喜欢这个项目，想模仿这个写😂
> 
> 哈哈没事，可能是文件 IO 问题导致 cache 读错了，后面我再找找其他设备查下； 你的项目很赞！有关软光栅的问题，可以随时开 issue 一起探讨~

好的，谢谢
