### ISSUE TITLE
Run-Time Check Failure

### ISSUE THREAD

**Issue by Xachi** [keith2018/SoftGLRender#52]
Stack around the variable 'texMapMode' was corrupted.

**Comment by Civitasv** [comment]
I also encounter this error.

**Comment by Xachi** [comment]
当时过了一会好像就解决了，你看看是不是没在独显上运行

**Comment by Civitasv** [comment]
应该是在独显上运行的才对

![image](https://github.com/keith2018/SoftGLRender/assets/37768049/1b7e3b85-c0c2-4f88-8636-24a7a2eff2df)

**Comment by Xachi** [comment]
你检查一下模型路径

**Comment by Civitasv** [comment]
Load Model 应该是成功了的
![image](https://github.com/keith2018/SoftGLRender/assets/37768049/1a70654c-590c-4fcb-80fb-cbd50c49d6d4)
路径应该也没问题
![image](https://github.com/keith2018/SoftGLRender/assets/37768049/03871727-f2cf-4cc6-a25f-805992b3e33b)

**Comment by Xachi** [comment]
Release编译下或者
https://blog.csdn.net/m0_75160047/article/details/129866603

**Comment by Civitasv** [comment]
Release下编译确实就成功了，谢谢

**Comment by yuz1** [comment]
问题不在于Release编译，而是这行

https://github.com/keith2018/SoftGLRender/blob/2312f58e6513fc6022107a1f153f1018d6b8c1e7/src/Viewer/ModelLoader.cpp#L354C3-L354C3

查看assimp内部实现可知应该传入size为2的数组。

已提交合并请求

@Civitasv

**Comment by keith2018** [comment]
> 问题不在于Release编译，而是这行
> 
> https://github.com/keith2018/SoftGLRender/blob/2312f58e6513fc6022107a1f153f1018d6b8c1e7/src/Viewer/ModelLoader.cpp#L354C3-L354C3
> 
> 查看assimp内部实现可知应该传入size为2的数组。
> 
> 已提交合并请求
> 
> @Civitasv

是的，之前的实现有问题，uv的 mapmode需要分别读出，感谢PR~

另外这里做了进一步修复 #55

**Comment by Civitasv** [comment]
> 问题不在于Release编译，而是这行
> 
> https://github.com/keith2018/SoftGLRender/blob/2312f58e6513fc6022107a1f153f1018d6b8c1e7/src/Viewer/ModelLoader.cpp#L354C3-L354C3
> 
> 查看assimp内部实现可知应该传入size为2的数组。
> 
> 已提交合并请求
> 
> @Civitasv

谢谢！
