### ISSUE TITLE
调试异常

### ISSUE THREAD

**Issue by yuz1** [keith2018/SoftGLRender#53]
https://github.com/keith2018/SoftGLRender/blob/2312f58e6513fc6022107a1f153f1018d6b8c1e7/src/Render/Software/RendererSoft.cpp#L548

当primitives_的capcity等于size的时候，上面这行会导致primitives_扩容，使得外部传入的triangle引用变量的地址失效。
点与线的处理好像也有类似问题。

**Comment by keith2018** [comment]
修改了实现方式： #56
可以看下是否还有问题
