### ISSUE TITLE
Unable to clone git repository

### ISSUE THREAD

**Issue by reinoslav** [keith2018/SoftGLRender#57]
Hello, I get the following error message while git clone: 

```
Downloading cache/IBL/07b81e737731cbb787d91c11436483f1.tex (524 KB)
Error downloading object: cache/IBL/07b81e737731cbb787d91c11436483f1.tex (6432a74): Smudge error: Error downloading cache/IBL/07b81e737731cbb787d91c11436483f1.tex (6432a74d02db0ddbee96042b5988b586b9798bf3d933d4f983990d2a9f05c651): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

I think those files should be not part of the repo? Thanks.

**Comment by keith2018** [comment]
The `cache/IBL/*.tex` files are pre-generated IBL textures, which can be used to speed up the initialization process of IBL effects, 

I've deleted these files due to github LFS quota.  (will be automatically generated at runtime.)
